/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.coffee.views.reports;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.temporal.TemporalAdjusters;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import vn.edu.coffee.controllers.BillCtrl;
import vn.edu.coffee.models.Bill;
import vn.edu.coffee.utils.DateUtils;
import vn.edu.coffee.views.HelperUI;

/**
 *
 * @author thuandv
 */
public class OrdersUI extends javax.swing.JFrame {

    /**
     * Creates new form OrdersUI
     */
    public OrdersUI() {
        initComponents();
        customComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jpanels = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtpFrom = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        dtpTo = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbItems = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Order Management");
        setResizable(false);

        jPanel2.setLayout(new java.awt.BorderLayout(4, 4));

        jpanels.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 4, 8));
        jpanels.setLayout(new javax.swing.BoxLayout(jpanels, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("From");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 8));
        jpanels.add(jLabel1);

        dtpFrom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jpanels.add(dtpFrom);

        jLabel2.setText("To");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 8, 1, 8));
        jpanels.add(jLabel2);

        dtpTo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jpanels.add(dtpTo);

        jLabel3.setText(" ");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 12));
        jpanels.add(jLabel3);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jpanels.add(btnSearch);

        jPanel2.add(jpanels, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 2, 1, 2));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(600, 404));

        tbItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Amount", "Total", "Check In", "Check out"
            }
        ));
        tbItems.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tbItems);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 8, 8, 8));
        jPanel3.setLayout(new java.awt.BorderLayout());

        lblInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(255, 51, 51));
        lblInfo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblInfo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel3.add(lblInfo, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        onLoadData();
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JFormattedTextField dtpFrom;
    private javax.swing.JFormattedTextField dtpTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanels;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JTable tbItems;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel tableModel;
    private BillCtrl billCtrl;
    private final String DATE_FORMAT = "dd/MM/yyyy";
    private final String DATE_FORMAT_SQL = "yyyy-MM-dd";

    private void customComponents() {
        setLocationRelativeTo(null);
        billCtrl = new BillCtrl();
        this.tableModel = (DefaultTableModel) tbItems.getModel();
        HelperUI.setTbColAlignment(tbItems, 0, SwingConstants.CENTER, 0);
        HelperUI.setTbColAlignment(tbItems, 1, SwingConstants.CENTER, 0);
        HelperUI.setTbColAlignment(tbItems, 2, SwingConstants.RIGHT, 0);
        HelperUI.setTbColAlignment(tbItems, 3, SwingConstants.CENTER, 120);
        HelperUI.setTbColAlignment(tbItems, 4, SwingConstants.CENTER, 120);

        HelperUI.setRowEditDisable(tbItems);
        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern(DATE_FORMAT);
        dtpFrom.setText(DateUtils.firstDayOfMonth(now).format(formatter));
        dtpTo.setText(DateUtils.lastDayOfMonth(now).format(formatter));
        onLoadData();
    }

    private void onLoadData() {
        try {
            List<Bill> list = billCtrl.find(
                    DateUtils.convertString2LocalDate(dtpFrom.getText()),
                    DateUtils.convertString2LocalDate(dtpTo.getText())
            );
            tableModel.setRowCount(0);
            tbItems.removeAll();
            float total = 0f;
            for (Bill item : list) {

                tableModel.addRow(new Object[]{
                    item.getId(),
                    item.getAmount(),
                    String.format("%(,.0f", item.getTotal()),
                    DateUtils.formatLocalDateTime(item.getCheckinAt()),
                    DateUtils.formatLocalDateTime(item.getCheckoutAt())
                });
            }
            tbItems.revalidate();
            tbItems.repaint();
            lblInfo.setText(String.format("Total: %(,.0f", total));
            tbItems.revalidate();
            tbItems.repaint();
        } catch (Exception e) {
            HelperUI.showMessage(this, e.getMessage());
        }
    }

    private String getDateSql(String val) {
        return LocalDate.parse(val, DateTimeFormatter.ofPattern(DATE_FORMAT))
                .format(DateTimeFormatter.ofPattern(DATE_FORMAT_SQL));
    }
}
