/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.coffee.views.orders;

import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import vn.edu.coffee.controllers.MenuItemCtrl;
import vn.edu.coffee.events.ActionAddMenuItem;
import vn.edu.coffee.events.MyActionEvent;
import vn.edu.coffee.models.MenuItem;
import vn.edu.coffee.views.HelperUI;

/**
 *
 * @author Ngoc Anh
 */
public class MenuItemPUI extends javax.swing.JPanel {

    /**
     * Creates new form MenuItemPUI
     */
    public MenuItemPUI() {
        initComponents();
        afternitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItems = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDown = new javax.swing.JButton();
        lblQty = new javax.swing.JLabel();
        btnUp = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menus");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 1, 4, 1));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 4, 8, 2));
        jPanel4.setLayout(new java.awt.BorderLayout(4, 0));
        jPanel4.add(txtSearch, java.awt.BorderLayout.CENTER);

        jLabel2.setText("Search");
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_START);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel4.add(btnSearch, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));

        tbItems.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        tbItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price"
            }
        ));
        tbItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbItems);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 8, 4));

        btnDown.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDown.setText("-");
        btnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownActionPerformed(evt);
            }
        });
        jPanel2.add(btnDown);

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQty.setText("1");
        jPanel2.add(lblQty);

        btnUp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUp.setText("+");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });
        jPanel2.add(btnUp);

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setText("Add Item");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);

        jPanel3.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        onItemAmountUp();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        onUpDown(1);
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownActionPerformed
        onUpDown(-1);
    }//GEN-LAST:event_btnDownActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        onLoadData();
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTable tbItems;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
    MenuItemCtrl ctrl;
    private DefaultTableModel tbModel;
    
    private void afternitComponents() {
//        btnDown.setEnabled(false);
        ctrl = new MenuItemCtrl();
        this.tbModel = (DefaultTableModel) tbItems.getModel();
        btnAdd.setEnabled(false);
        this.tbItems.getSelectionModel().addListSelectionListener(new OnTableSelect());
        HelperUI.setTbColAlignment(tbItems, 0, SwingConstants.CENTER, 50);
        HelperUI.setTbColAlignment(tbItems, 1, SwingConstants.LEFT, 0);
        HelperUI.setTbColAlignment(tbItems, 2, SwingConstants.RIGHT, 0);
        HelperUI.setRowEditDisable(tbItems);
        onLoadData();
    }
    
    List<MenuItem> items;
    
    private void onLoadData() {
        tbItems.removeAll();
        tbModel.setRowCount(0);
        items = ctrl.find(txtSearch.getText());
        for (MenuItem menuItem : items) {
            
            tbModel.addRow(new Object[]{
                menuItem.getId(),
                menuItem.getName(),
                String.format("%(,.0f", menuItem.getPrice()),});
        }

//        lblTotal.setText(String.format("Total: %d Records", items.size()));
        tbItems.revalidate();
        tbItems.repaint();
    }
    public ActionAddMenuItem setRowSelected;
    
    private MenuItem itemSelected;

    private void onItemAmountUp() {
        if (itemSelected != null && setRowSelected != null) {
            setRowSelected.onAction(itemSelected, quantity);
            quantity = 1;
            lblQty.setText(quantity + "");
//            btnDown.setEnabled(quantity > 1);
//            itemSelected = null;
            btnAdd.setEnabled(false);
            onLoadData();
        }
    }
    
    private Integer quantity = 1;

    private void onUpDown(int step) {
        quantity += step;
//        btnDown.setEnabled(quantity > 1);
        lblQty.setText(quantity + "");
    }
    
    private class OnTableSelect implements ListSelectionListener {
        
        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int inx = tbItems.getSelectedRow();
                if (inx != -1) {
                    long id = Long.parseLong(tbModel.getValueAt(inx, 0).toString());
                    for (MenuItem item : items) {
                        if (item.getId() == id) {
                            itemSelected = item;
                            btnAdd.setEnabled(true);
                            break;
                        }
                    }
                }
            }
        }
    }
}
