/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vn.edu.coffee.views.orders;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author Ngoc Anh
 */
public class OrderConfirmDialog extends javax.swing.JDialog {

    /**
     * Creates new form OrderConfirmDialog
     */
    public OrderConfirmDialog(java.awt.Frame parent, String table, ActionListener event) {
        super(parent, "Confirm", true);
        initComponents();
        afterInitComponents(parent, event, table);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afterInitComponents(java.awt.Frame parent, ActionListener event, String table) {
        setLayout(new BorderLayout(20, 20));
        JLabel messageLabel = new JLabel(String.format("You ordered for [%s]. Please confirm.", table));
        messageLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 20, 3, 20));
        add(messageLabel, BorderLayout.CENTER);

        // Create an "OK" button
        JButton okButton = new JButton("OK");
        add(okButton, BorderLayout.SOUTH);

        // Add an ActionListener to the "OK" button
        okButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (event != null) {
                    event.actionPerformed(e);
                }
                
                dispose();  // Close the dialog
            }
        });

        // Set size of the dialog
        setSize(300, 150);
        setLocationRelativeTo(parent);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
