/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.coffee.views.orders;

import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import vn.edu.coffee.controllers.BillCtrl;
import vn.edu.coffee.controllers.OrderDetailCtrl;
import vn.edu.coffee.events.MyActionEvent;
import vn.edu.coffee.models.OrderDetail;
import vn.edu.coffee.models.TableFood;
import vn.edu.coffee.views.HelperUI;

/**
 *
 * @author Ngoc Anh
 */
public class OrderDetailPUI extends javax.swing.JPanel {

    /**
     * Creates new form MenuItemPUI
     */
    public OrderDetailPUI() {
        initComponents();
        afternitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItems = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        btnCheckOut = new javax.swing.JButton();
        btnItemSub = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        lblTitle.setBackground(new java.awt.Color(102, 204, 255));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Table ...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tbItems.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 10));
        tbItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Amount", "Price", "Total"
            }
        ));
        tbItems.setEnabled(false);
        tbItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbItems.setShowGrid(true);
        jScrollPane1.setViewportView(tbItems);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout());

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 51, 51));
        lblTotal.setText("Total");
        lblTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 8, 3, 1));
        jPanel3.add(lblTotal, java.awt.BorderLayout.CENTER);

        btnCheckOut.setBackground(new java.awt.Color(255, 102, 102));
        btnCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckOut.setText("Check Out");
        btnCheckOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 12, 4, 12));
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        jPanel3.add(btnCheckOut, java.awt.BorderLayout.LINE_END);

        btnItemSub.setBackground(new java.awt.Color(51, 255, 0));
        btnItemSub.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnItemSub.setText("-");
        btnItemSub.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 1, 5, 1));
        btnItemSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemSubActionPerformed(evt);
            }
        });
        jPanel3.add(btnItemSub, java.awt.BorderLayout.PAGE_START);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        onCheckOut();
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnItemSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemSubActionPerformed
        onItemDown();
    }//GEN-LAST:event_btnItemSubActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnItemSub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tbItems;
    // End of variables declaration//GEN-END:variables
    OrderDetailCtrl ctrl;
    BillCtrl billCtrl;
    private DefaultTableModel tbModel;
    private TableFood table;
    List<OrderDetail> orders;

    public MyActionEvent<TableFood> onOrderCheckOut;

    private void afternitComponents() {
        btnItemSub.setVisible(false);
        ctrl = new OrderDetailCtrl();
        billCtrl = new BillCtrl();
        this.tbModel = (DefaultTableModel) tbItems.getModel();
        HelperUI.setTbColAlignment(tbItems, 0, SwingConstants.LEFT, 0);
        HelperUI.setTbColAlignment(tbItems, 1, SwingConstants.CENTER, 50);
        HelperUI.setTbColAlignment(tbItems, 2, SwingConstants.RIGHT, 0);
        HelperUI.setTbColAlignment(tbItems, 3, SwingConstants.RIGHT, 0);
        onLoadData(null);
        HelperUI.setRowEditDisable(tbItems);
    }

    public void onLoadData(TableFood table) {
        this.table = table;
        lblTitle.setVisible(table != null);
        jScrollPane1.setVisible(table != null);
        lblTotal.setVisible(table != null);
        btnCheckOut.setVisible(table != null);
        float total = 0.f;
        if (table != null) {
            lblTitle.setText(table.getName());
            tbItems.removeAll();
            tbModel.setRowCount(0);
            orders = ctrl.findByBillId(table.getIdBill());
            for (OrderDetail item : orders) {
                tbModel.addRow(new Object[]{
                    item.getName(),
                    item.getAmount(),
                    String.format("%(,.0f", item.getPrice()),
                    String.format("%(,.0f", item.getTotal())
                });
                total += item.getTotal();
            }

            lblTotal.setText(String.format("Total: %d Records. Total price: %(,.0f", orders.size(), total));
        }

    }

    private void onCheckOut() {
        if (onOrderCheckOut != null) {
            onOrderCheckOut.onAction(table);
        }
    }

    private void onItemDown() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
