/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vn.edu.coffee.views.orders;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import vn.edu.coffee.events.MyActionEvent;
import vn.edu.coffee.models.TableFood;

/**
 *
 * @author Ngoc Anh
 */
public class TableItemCard extends javax.swing.JPanel {

    /**
     * Creates new form TableItemCard
     */
    public MyActionEvent<TableFood> onClick;

    public TableItemCard() {
        initComponents();
    }

    private TableFood table;

    public TableItemCard(TableFood item) {
        this();
        setPreferredSize(new Dimension(100, 100));
        this.table = item;
        lblTitle.setText(item.getName());
        lblStatus.setText(item.getIdBill() == 0 ? "Available" : "Busy");
        this.setBackground(table.getIdBill() > 0 ? Color.YELLOW : Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        lblTitle.setForeground(new java.awt.Color(255, 51, 51));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        add(lblTitle, java.awt.BorderLayout.PAGE_START);

        lblStatus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblStatus, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (table != null && onClick != null) {
            onClick.onAction(table);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
    private static final int ARC_WIDTH = 20; // Width of the arc
    private static final int ARC_HEIGHT = 20;
     @Override
    protected void paintComponent(Graphics g) {
//         Graphics2D g2d = (Graphics2D) g;
//        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        g2d.fillRoundRect(20, 20, getWidth() - 40, getHeight() - 40, 50, 50);
//        super.paintComponent(g); // Always call the superclass method first
       
        
        Graphics2D g2d = (Graphics2D) g;

        // Enable antialiasing for smoother edges
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Create a round rectangle
        RoundRectangle2D roundedRect = new RoundRectangle2D.Double(
                0, 0, getWidth() - 1, getHeight() - 1, ARC_WIDTH, ARC_HEIGHT);

        // Clip to the round rectangle
        g2d.setClip(roundedRect);

        // Draw the background
        g2d.setColor(getBackground());
        g2d.fill(roundedRect);

        // Optionally, draw a border (not rounded)
        g2d.setColor(Color.GRAY);
        g2d.draw(roundedRect);
        super.paintComponent(g);
    }


}
