/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.coffee.views.menuitem;

import vn.edu.coffee.views.*;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import vn.edu.coffee.controllers.MenuItemCtrl;
import vn.edu.coffee.events.MyActionEvent;
import vn.edu.coffee.models.MenuItem;

/**
 *
 * @author Ngoc Anh
 */
public class MenuItemUI extends BaseFrame {

    /**
     * Creates new form TableFoodUI
     */
    public MenuItemUI() {
        initComponents();
        afterInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAdd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnUpdate = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnDel = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItems = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MenuItem Management");

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(true);

        btnAdd.setText("Add New");
        btnAdd.setFocusable(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAdd);
        jToolBar1.add(jSeparator1);

        btnUpdate.setText("Update");
        btnUpdate.setActionCommand("");
        btnUpdate.setFocusable(false);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUpdate);
        jToolBar1.add(jSeparator2);

        btnDel.setText("Delete");
        btnDel.setToolTipText("");
        btnDel.setFocusable(false);
        btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDel);
        jToolBar1.add(jSeparator3);

        jLabel1.setText("Search");
        jToolBar1.add(jLabel1);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jToolBar1.add(txtSearch);

        btnSearch.setText("Search");
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSearch);

        jToolBar2.setRollover(true);
        jToolBar1.add(jToolBar2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tbItems.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        tbItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Status"
            }
        ));
        tbItems.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbItems.setShowGrid(true);
        tbItems.setUpdateSelectionOnSort(false);
        jScrollPane1.setViewportView(tbItems);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        onAdd();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        onUpdate();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        onDelete();
    }//GEN-LAST:event_btnDelActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        onLoadData();
    }//GEN-LAST:event_txtSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable tbItems;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel tableModel;
    private MenuItem itemUpdate;
    private MenuItemCtrl ctrl;

    private void afterInitComponents() {
        ctrl = new MenuItemCtrl();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.tableModel = (DefaultTableModel) tbItems.getModel();
        this.tbItems.getSelectionModel().addListSelectionListener(new OnTableSelect());
        HelperUI.setRowEditDisable(tbItems);
        HelperUI.setTbColAlignment(tbItems, 0, SwingConstants.CENTER, 50);
        HelperUI.setTbColAlignment(tbItems, 1, SwingConstants.LEFT, 0);
        HelperUI.setTbColAlignment(tbItems, 2, SwingConstants.RIGHT, 0);    
        HelperUI.setTbColAlignment(tbItems, 3, SwingConstants.CENTER, 80);
        onLoadData();
    }

    private void onLoadData() {
        
        this.itemUpdate = null;
        setEnabledButton();
        this.tbItems.removeAll();
        this.tableModel.setRowCount(0);
        for (MenuItem item : ctrl.find(txtSearch.getText())) {
            tableModel.addRow(new Object[]{
                item.getId(), item.getName(),
                String.format("%(,.0f", item.getPrice()),
                item.isStatus() ? "Available" : "Unavailable"
            });
        }
        this.tbItems.revalidate();
        this.tbItems.repaint();
    }

    private void onUpdate() {
        FormMenuItem form = new FormMenuItem(this, this.itemUpdate);
        form.addEvent = new MyActionEvent<MenuItem>() {
            @Override
            public void onAction(MenuItem item) {
                ctrl.update(item.getId(), item);
                onLoadData();
            }
        };
        form.setVisible(true);
    }

    private void onDelete() {
        if (itemUpdate != null) {
            ctrl.remove(itemUpdate.getId());
            showSuccess();
            onLoadData();
        }
    }

    private void onAdd() {
        FormMenuItem form = new FormMenuItem(this, null);
        form.addEvent = new MyActionEvent<MenuItem>() {
            @Override
            public void onAction(MenuItem item) {
                ctrl.add(item);
                onLoadData();
            }
        };
        form.setVisible(true);
    }

    private class OnTableSelect implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                int inx = tbItems.getSelectedRow();
                if (inx != -1) {
                    long id = Long.parseLong(tableModel.getValueAt(inx, 0).toString());
                    itemUpdate = ctrl.findById(id);
                    setEnabledButton();
                }
            }
        }
    }

    private void setEnabledButton() {
        boolean enabled = itemUpdate != null;
        btnUpdate.setEnabled(enabled);
        btnDel.setEnabled(enabled);
    }

}
